// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://venyacfirliborljysqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbnlhY2ZpcmxpYm9ybGp5c3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Njc0MDEsImV4cCI6MjA2MDI0MzQwMX0.EYFkSJAEYi5d8sjChRaTeybMvLkhJmmXNZGSgyepd8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);